### PR TITLE
Adding translations

### PR DESCRIPTION
**Pull request by mateusjunges**
This PR adds translations to the `InvalidConversion` exception message.

Before this pull request, the exception displays the exception message only in english. 
Now, you can set your `config/app.php` `locale` key to your location and use the correct language to the exception message, like `pt-br` for portuguese, `en` for english and `it` for italian.

This is the complete list of supported languages:
- Portuguese (`pt-br`)
- English (`en`)
- French (`fr`)
- Italian (`it`)
- Russian (`ru`)

### CODE REVIEW

**Comment by Jack97** [comment]
Hi @mateusjunges 

Firstly, thank you for your interest in our package - we're very appreciative of any contributions.

My only concern with this PR is that it affects the maintainability of the code base as nobody here is multilingual. It's likely that we'll create new exception classes throughout the life cycle of this project, and we can't rely on external help to translate the messages to all of the languages above.

I do however really like this idea, and I'd definitely merge this if it were to only provide `en` out of the box.

**Comment by mateusjunges** [comment]
@Jack97 
You mean remove all languages but english to provide a maintainable code, but still providing an option to the user to translate the messages? I can remove the other languages if you agree with it.

**Comment by Jack97** [comment]
Yep that's right :)

**Comment by mateusjunges** [comment]
@Jack97 it's done!

**Comment by r1chm8** [comment]
Upon further reflection we've decided to leave this here for now. This exception should be caught and handled in the app before a message is returned to the user. If we do decide to expose external error messages in the future we may reconsider.

**Pull request closed without merging**
